### PR TITLE
created cs switch slidedeck

### PR DESCRIPTION
**Pull request by wandercode**
Jira: https://brainchildschool.atlassian.net/browse/BRAIN-430

image
image
image

### CODE REVIEW

**Comment by wandercode** [comment]
image

**Review by sneha-brainchild — COMMENTED** [review]
compare to paragraph contents, lists will be more attractive

**Review by sneha-brainchild — COMMENTED** [review]
compare to paragraph content lists will be more attractive

**Review by VishnuKulakkattu — APPROVED** [review]

**Comment by wandercode** [comment]
image
image

**Review by sneha-brainchild — DISMISSED** [review]

**Pull request merged**
